---
# Source: helm-guestbook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: poc-prod2-macroservice
  labels:
    app: poc-prod2-macroservice    
    athena.io/logicalenv: prod
    athena.io/chart: helm-guestbook-0.6.0
    athena.io/release: release-name
    athena.io/service: Helm
    athena.io/namespace: argocd-poc-prod2-platform
    atheaa.io/affinity: unspecified
  annotations:
    kong.athena.io/host: macroservice-clinicals.*
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: poc-prod2-macroservice
    release: release-name
---
# Source: helm-guestbook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-prod2-macroservice
  labels:
    app: poc-prod2-macroservice
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: poc-prod2-macroservice
  template:
    metadata:
      labels:
        app: poc-prod2-macroservice
        deploymentid: time-1692961283        
        athena.io/logicalenv: prod
        athena.io/chart: helm-guestbook-0.6.0
        athena.io/release: release-name
        athena.io/service: Helm
        athena.io/namespace: argocd-poc-prod2-platform
        atheaa.io/affinity: unspecified
    spec:
      containers:
        - name: poc-prod2-macroservice
          image: "gcr.io/heptio-images/ks-guestbook-demo:0.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: Location
      #           operator: In
      #           values:
      #           - us-west-2
