---
# Source: helm-guestbook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: poc-qad1-macroservice-pr1122
  labels:
    app: poc-qad1-macroservice-pr1122    
    athena.io/logicalenv: qad
    athena.io/chart: helm-guestbook-0.4.0
    athena.io/release: release-name
    athena.io/service: Helm
    athena.io/namespace: argocd-poc-qad1-platform
    atheaa.io/affinity: unspecified
  annotations:
    kong.athena.io/host: macroservice-clinicals.*
    kong.athena.io/path: /pr1122
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: poc-qad1-macroservice-pr1122
    release: release-name
---
# Source: helm-guestbook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-qad1-macroservice-pr1122
  labels:
    app: poc-qad1-macroservice-pr1122
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: poc-qad1-macroservice-pr1122
  template:
    metadata:
      labels:
        app: poc-qad1-macroservice-pr1122
        deploymentid: time-1692961137        
        athena.io/logicalenv: qad
        athena.io/chart: helm-guestbook-0.4.0
        athena.io/release: release-name
        athena.io/service: Helm
        athena.io/namespace: argocd-poc-qad1-platform
        atheaa.io/affinity: unspecified
    spec:
      containers:
        - name: poc-qad1-macroservice-pr1122
          image: "gcr.io/heptio-images/ks-guestbook-demo:0.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: Location
      #           operator: In
      #           values:
      #           - us-east-1
