---
# Source: helm-guestbook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: poc-dev1-macroservice-qwe222
  labels:
    app: poc-dev1-macroservice-qwe222    
    athena.io/logicalenv: dev
    athena.io/chart: helm-guestbook-0.2.0
    athena.io/release: release-name
    athena.io/service: Helm
    athena.io/namespace: argocd-poc-dev1-platform
  annotations:
    kong.athena.io/host: macroservice-clinicals.*
    kong.athena.io/path: /qwe222
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: poc-dev1-macroservice-qwe222
    release: release-name
---
# Source: helm-guestbook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-dev1-macroservice-qwe222
  labels:
    app: poc-dev1-macroservice-qwe222
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: poc-dev1-macroservice-qwe222
  template:
    metadata:
      labels:
        app: poc-dev1-macroservice-qwe222
        deploymentid: time-1692890387        
        athena.io/logicalenv: dev
        athena.io/chart: helm-guestbook-0.2.0
        athena.io/release: release-name
        athena.io/service: Helm
        athena.io/namespace: argocd-poc-dev1-platform
    spec:
      containers:
        - name: poc-dev1-macroservice-qwe222
          image: "gcr.io/heptio-images/ks-guestbook-demo:0.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: Location
                operator: In
                values:
                - us-east-1
